project:
  type: website

website:
  title: "A blog about psychometrics and related topics"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/niadme
format:
  html:
    theme: flatly
    css: styles.css

editor: visual

